---

- name: "Creating docker-overlay2 storage script.."
  template:
    src: create-docker-overlay2-lvm.j2
    dest: /root/create-docker-overlay2-lvm.sh
    owner: root
    group: root
    mode: 755

- name: "Creating docker-overlay2 storage.."
  shell: /root/create-docker-overlay2-lvm.sh 2>&1 | /bin/tee -a /root/create-docker-overlay2-lvm.log
  args:
    executable: /bin/sh
    chdir: /root
    creates: /root/create-docker-overlay2-lvm.log

