---

- name: "Initialise docker swarm on first manager"
  shell: '/bin/docker swarm init > /root/docker-swarm-init.log 2>&1'
  args:
    chdir: /root
    creates: /root/docker-swarm-init.log


# Grab the Swarm join tokens, used in later tasks
- name: "Get swarm manager join token"
  shell: /bin/docker swarm join-token -q manager
  register: manager_token

- name: "Get swarm worker join token"
  shell: /bin/docker swarm join-token -q worker
  register: worker_token

