---

#- debug:
#    msg: "manager token is: {{ hostvars[groups['primary'][0]]['manager_token'].stdout }} IP is: {{ hostvars[groups['primary'][0]]['ansible_eth0']['ipv4']['address'] }}"

- name: "Join manager to cluster"
  shell: /bin/docker swarm join --token {{ hostvars[groups['primary'][0]]['manager_token'].stdout }} {{ hostvars[groups['primary'][0]]['ansible_eth0']['ipv4']['address'] }} > /root/swarm-manager-join.log
  args:
    creates: /root/swarm-manager-join.log

